# Generated by Django 5.0.2 on 2024-02-22 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
