# Generated by Django 5.0.2 on 2024-02-23 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0003_user_role_with_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role_with_user",
        ),
    ]
