# Generated by Django 5.0.2 on 2024-02-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0007_remove_user_role_data_alter_grouppermission_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="crud.role"
            ),
        ),
    ]
