# Generated by Django 5.0.2 on 2024-02-23 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0009_rename_role_id_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="crud.role"
            ),
        ),
    ]
